# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /mada/users/gmejiama/Documents/vivado-risc-v/board/genesys2/top.xdc

# XDC: /mada/users/gmejiama/Documents/vivado-risc-v/board/genesys2/sdc.xdc

# XDC: /mada/users/gmejiama/Documents/vivado-risc-v/board/genesys2/uart.xdc

# XDC: /mada/users/gmejiama/Documents/vivado-risc-v/board/genesys2/ethernet.xdc

# TCL: /mada/users/gmejiama/Documents/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/syn/vivado/sync_reset.tcl

# TCL: /mada/users/gmejiama/Documents/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/syn/vivado/axis_async_fifo.tcl

# TCL: /mada/users/gmejiama/Documents/vivado-risc-v/ethernet/verilog-ethernet/syn/vivado/eth_mac_fifo.tcl

# TCL: /mada/users/gmejiama/Documents/vivado-risc-v/ethernet/verilog-ethernet/syn/vivado/eth_mac_1g_rgmii.tcl

# TCL: /mada/users/gmejiama/Documents/vivado-risc-v/board/timing-constraints.tcl

# Block Designs: bd/riscv/riscv.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv || ORIG_REF_NAME==riscv} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_smc_1_0/riscv_axi_smc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_axi_smc_1_0 || ORIG_REF_NAME==riscv_axi_smc_1_0} -quiet] -quiet

# Block Designs: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/bd_fe52.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_0/bd_fe52_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_4/bd_fe52_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_5/bd_fe52_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_6/bd_fe52_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_14/bd_fe52_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_mem_reset_control_0_0/riscv_mem_reset_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_mem_reset_control_0_0 || ORIG_REF_NAME==riscv_mem_reset_control_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_mig_7series_0_0 || ORIG_REF_NAME==riscv_mig_7series_0_0} -quiet] -quiet

<<<<<<< HEAD
# IP: bd/riscv/ip/riscv_Ethernet_0/riscv_Ethernet_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_Ethernet_0 || ORIG_REF_NAME==riscv_Ethernet_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_SD_0/riscv_SD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_SD_0 || ORIG_REF_NAME==riscv_SD_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_UART_0/riscv_UART_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_UART_0 || ORIG_REF_NAME==riscv_UART_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_XADC_0 || ORIG_REF_NAME==riscv_XADC_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_ethernet_stream_0_0/riscv_ethernet_stream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_ethernet_stream_0_0 || ORIG_REF_NAME==riscv_ethernet_stream_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_io_axi_m_0/riscv_io_axi_m_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_io_axi_m_0 || ORIG_REF_NAME==riscv_io_axi_m_0} -quiet] -quiet

# Block Designs: bd/riscv/ip/riscv_io_axi_m_0/bd_0/bd_9c60.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_0/bd_9c60_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_1/bd_9c60_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_2/bd_9c60_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_3/bd_9c60_psr_aclk2_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_4/bd_9c60_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_5/bd_9c60_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_6/bd_9c60_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_7/bd_9c60_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_8/bd_9c60_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_9/bd_9c60_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_10/bd_9c60_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_11/bd_9c60_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_12/bd_9c60_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_13/bd_9c60_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_14/bd_9c60_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_15/bd_9c60_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_16/bd_9c60_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_17/bd_9c60_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_18/bd_9c60_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_19/bd_9c60_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_20/bd_9c60_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_21/bd_9c60_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_22/bd_9c60_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_23/bd_9c60_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_24/bd_9c60_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_25/bd_9c60_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_26/bd_9c60_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_27/bd_9c60_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_28/bd_9c60_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_29/bd_9c60_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_30/bd_9c60_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_31/bd_9c60_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_32/bd_9c60_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_33/bd_9c60_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/riscv_io_axi_s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_io_axi_s_0 || ORIG_REF_NAME==riscv_io_axi_s_0} -quiet] -quiet

# Block Designs: bd/riscv/ip/riscv_io_axi_s_0/bd_0/bd_9a00.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_0/bd_9a00_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_1/bd_9a00_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_2/bd_9a00_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_3/bd_9a00_psr_aclk2_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_4/bd_9a00_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_5/bd_9a00_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_6/bd_9a00_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_7/bd_9a00_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_8/bd_9a00_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_9/bd_9a00_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_10/bd_9a00_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_11/bd_9a00_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_12/bd_9a00_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_13/bd_9a00_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_14/bd_9a00_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_15/bd_9a00_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_16/bd_9a00_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_17/bd_9a00_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_18/bd_9a00_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_19/bd_9a00_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_20/bd_9a00_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_21/bd_9a00_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_22/bd_9a00_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_23/bd_9a00_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_24/bd_9a00_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_25/bd_9a00_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_26/bd_9a00_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_27/bd_9a00_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_28/bd_9a00_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_29/bd_9a00_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_30/bd_9a00_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_31/bd_9a00_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_32/bd_9a00_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_33/bd_9a00_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_34/bd_9a00_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_35/bd_9a00_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_36/bd_9a00_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_37/bd_9a00_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_38/bd_9a00_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_39/bd_9a00_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_40/bd_9a00_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_41/bd_9a00_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_42/bd_9a00_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_43/bd_9a00_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_44/bd_9a00_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_45/bd_9a00_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_46/bd_9a00_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_47/bd_9a00_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_48/bd_9a00_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_49/bd_9a00_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_50/bd_9a00_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_51/bd_9a00_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_52/bd_9a00_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_53/bd_9a00_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_54/bd_9a00_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_55/bd_9a00_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/riscv/ip/riscv_xlconcat_0_0/riscv_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_xlconcat_0_0 || ORIG_REF_NAME==riscv_xlconcat_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_RocketChip_0 || ORIG_REF_NAME==riscv_RocketChip_0} -quiet] -quiet

=======
>>>>>>> sd-card-picorv32
# IP: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_clk_wiz_0_0 || ORIG_REF_NAME==riscv_clk_wiz_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_util_ds_buf_0_0 || ORIG_REF_NAME==riscv_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_util_vector_logic_0_0/riscv_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_util_vector_logic_0_0 || ORIG_REF_NAME==riscv_util_vector_logic_0_0} -quiet] -quiet

<<<<<<< HEAD
=======
# IP: bd/riscv/ip/riscv_picorv32_axi_0_1/riscv_picorv32_axi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_picorv32_axi_0_1 || ORIG_REF_NAME==riscv_picorv32_axi_0_1} -quiet] -quiet

# IP: bd/riscv/ip/riscv_xbar_0/riscv_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_xbar_0 || ORIG_REF_NAME==riscv_xbar_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_interconnect_0_0/riscv_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_axi_interconnect_0_0 || ORIG_REF_NAME==riscv_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_uart_0_0/riscv_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_uart_0_0 || ORIG_REF_NAME==riscv_uart_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_xlconstant_0_0/riscv_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_xlconstant_0_0 || ORIG_REF_NAME==riscv_xlconstant_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_data_fifo_0_0/riscv_axi_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_axi_data_fifo_0_0 || ORIG_REF_NAME==riscv_axi_data_fifo_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_jtag_axi_0_0/riscv_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_jtag_axi_0_0 || ORIG_REF_NAME==riscv_jtag_axi_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_interconnect_1_0/riscv_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_axi_interconnect_1_0 || ORIG_REF_NAME==riscv_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_gpio_0_0/riscv_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_axi_gpio_0_0 || ORIG_REF_NAME==riscv_axi_gpio_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axil_ram_0_0/riscv_axil_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_axil_ram_0_0 || ORIG_REF_NAME==riscv_axil_ram_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_pc_3/riscv_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_pc_3 || ORIG_REF_NAME==riscv_auto_pc_3} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_us_0/riscv_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_us_0 || ORIG_REF_NAME==riscv_auto_us_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_us_1/riscv_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_us_1 || ORIG_REF_NAME==riscv_auto_us_1} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_ds_0/riscv_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_ds_0 || ORIG_REF_NAME==riscv_auto_ds_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_pc_0/riscv_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_pc_0 || ORIG_REF_NAME==riscv_auto_pc_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_ds_1/riscv_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_ds_1 || ORIG_REF_NAME==riscv_auto_ds_1} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_pc_1/riscv_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_pc_1 || ORIG_REF_NAME==riscv_auto_pc_1} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_ds_2/riscv_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_ds_2 || ORIG_REF_NAME==riscv_auto_ds_2} -quiet] -quiet

# IP: bd/riscv/ip/riscv_auto_pc_2/riscv_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_auto_pc_2 || ORIG_REF_NAME==riscv_auto_pc_2} -quiet] -quiet

>>>>>>> sd-card-picorv32
# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_smc_1_0/ooc.xdc

# XDC: bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0/user_design/constraints/riscv_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==riscv_mig_7series_0_0 || ORIG_REF_NAME==riscv_mig_7series_0_0} -quiet] -quiet

# XDC: bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0/user_design/constraints/riscv_mig_7series_0_0_ooc.xdc

<<<<<<< HEAD
# XDC: bd/riscv/ip/riscv_XADC_0/riscv_XADC_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_XADC_0 || ORIG_REF_NAME==riscv_XADC_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_1/bd_9c60_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_1/bd_9c60_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_2/bd_9c60_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_2/bd_9c60_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_3/bd_9c60_psr_aclk2_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_3/bd_9c60_psr_aclk2_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_4/bd_9c60_arsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_5/bd_9c60_rsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_6/bd_9c60_awsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_7/bd_9c60_wsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_8/bd_9c60_bsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_12/bd_9c60_s00a2s_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_13/bd_9c60_sarn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_14/bd_9c60_srn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_15/bd_9c60_sawn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_16/bd_9c60_swn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_17/bd_9c60_sbn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_21/bd_9c60_s01a2s_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_22/bd_9c60_sarn_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_23/bd_9c60_srn_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_24/bd_9c60_sawn_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_25/bd_9c60_swn_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_26/bd_9c60_sbn_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_27/bd_9c60_m00s2a_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_28/bd_9c60_m00arn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_29/bd_9c60_m00rn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_30/bd_9c60_m00awn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_31/bd_9c60_m00wn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_32/bd_9c60_m00bn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_m_0/ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_1/bd_9a00_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_1/bd_9a00_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_2/bd_9a00_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_2/bd_9a00_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_3/bd_9a00_psr_aclk2_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_3/bd_9a00_psr_aclk2_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_4/bd_9a00_arinsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_5/bd_9a00_rinsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_6/bd_9a00_awinsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_7/bd_9a00_winsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_8/bd_9a00_binsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_9/bd_9a00_aroutsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_10/bd_9a00_routsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_11/bd_9a00_awoutsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_12/bd_9a00_woutsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_13/bd_9a00_boutsw_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_14/bd_9a00_arni_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_15/bd_9a00_rni_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_16/bd_9a00_awni_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_17/bd_9a00_wni_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_18/bd_9a00_bni_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_22/bd_9a00_s00a2s_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_23/bd_9a00_sarn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_24/bd_9a00_srn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_25/bd_9a00_sawn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_26/bd_9a00_swn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_27/bd_9a00_sbn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_28/bd_9a00_m00s2a_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_29/bd_9a00_m00arn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_30/bd_9a00_m00rn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_31/bd_9a00_m00awn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_32/bd_9a00_m00wn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_33/bd_9a00_m00bn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_35/bd_9a00_m01s2a_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_36/bd_9a00_m01arn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_37/bd_9a00_m01rn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_38/bd_9a00_m01awn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_39/bd_9a00_m01wn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_40/bd_9a00_m01bn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_42/bd_9a00_m02s2a_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_43/bd_9a00_m02arn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_44/bd_9a00_m02rn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_45/bd_9a00_m02awn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_46/bd_9a00_m02wn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_47/bd_9a00_m02bn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_49/bd_9a00_m03s2a_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_50/bd_9a00_m03arn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_51/bd_9a00_m03rn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_52/bd_9a00_m03awn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_53/bd_9a00_m03wn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_54/bd_9a00_m03bn_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_io_axi_s_0/ooc.xdc

=======
>>>>>>> sd-card-picorv32
# XDC: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_clk_wiz_0_0 || ORIG_REF_NAME==riscv_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_clk_wiz_0_0 || ORIG_REF_NAME==riscv_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_clk_wiz_0_0 || ORIG_REF_NAME==riscv_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_util_ds_buf_0_0 || ORIG_REF_NAME==riscv_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_util_ds_buf_0_0 || ORIG_REF_NAME==riscv_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0_ooc.xdc

<<<<<<< HEAD
=======
# XDC: bd/riscv/ip/riscv_xbar_0/riscv_xbar_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_data_fifo_0_0/riscv_axi_data_fifo_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_axi_data_fifo_0_0 || ORIG_REF_NAME==riscv_axi_data_fifo_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_axi_data_fifo_0_0/riscv_axi_data_fifo_0_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_jtag_axi_0_0/constraints/jtag_axi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_jtag_axi_0_0 || ORIG_REF_NAME==riscv_jtag_axi_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_jtag_axi_0_0/riscv_jtag_axi_0_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_gpio_0_0/riscv_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_axi_gpio_0_0 || ORIG_REF_NAME==riscv_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_axi_gpio_0_0/riscv_axi_gpio_0_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_axi_gpio_0_0/riscv_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_axi_gpio_0_0 || ORIG_REF_NAME==riscv_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_auto_pc_3/riscv_auto_pc_3_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_us_0/riscv_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_auto_us_0 || ORIG_REF_NAME==riscv_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_auto_us_0/riscv_auto_us_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_us_1/riscv_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_auto_us_1 || ORIG_REF_NAME==riscv_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_auto_us_1/riscv_auto_us_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_ds_0/riscv_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_auto_ds_0 || ORIG_REF_NAME==riscv_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_auto_ds_0/riscv_auto_ds_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_pc_0/riscv_auto_pc_0_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_ds_1/riscv_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_auto_ds_1 || ORIG_REF_NAME==riscv_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_auto_ds_1/riscv_auto_ds_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_pc_1/riscv_auto_pc_1_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_ds_2/riscv_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==riscv_auto_ds_2 || ORIG_REF_NAME==riscv_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/riscv/ip/riscv_auto_ds_2/riscv_auto_ds_2_ooc.xdc

# XDC: bd/riscv/ip/riscv_auto_pc_2/riscv_auto_pc_2_ooc.xdc

>>>>>>> sd-card-picorv32
# XDC: bd/riscv/riscv_ooc.xdc
